# Generated by Django 3.2 on 2023-06-18 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alumno_imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno_Horario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('horario_ingreso', models.TimeField()),
                ('horario_salida', models.TimeField()),
                ('id_Alumnos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alumno')),
            ],
        ),
    ]
