# Generated by Django 3.2 on 2023-06-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_alumno_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno_horario',
            old_name='alumno',
            new_name='id_Alumnos',
        ),
        migrations.AlterField(
            model_name='alumno_horario',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
