# Generated by Django 3.2 on 2023-06-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230619_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno_horario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
