# Generated by Django 3.2 on 2023-06-27 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_alumno_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='alumno_horario',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='alumno_horario',
            name='id_Alumnos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='api.alumno'),
        ),
        migrations.AlterModelTable(
            name='alumno',
            table='alumno',
        ),
        migrations.AlterModelTable(
            name='alumno_horario',
            table='alumno_horario',
        ),
    ]
